Repository Pong-Arcade/ft_transcendence, pull requests merged in 2023-02, with the labels that each got.

#41 [FE] FEAT: 로비 유저 프로필에 최근전적 버튼을 내정보 버튼으로 변경 #37
  frontend/src/components/atoms/Button/Button.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/LogoutButton/LogoutButton.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
Labels: feat, fe

#47 [BE] 서버측에서 사용할 DTO 추가 #34
  backend/package-lock.json
  backend/package.json
  backend/src/auth/42/ft.strategy.ts
  backend/src/auth/42/mock.strategy.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/session/session.serializer.ts
  backend/src/dto/chatroom.list.dto.ts
  backend/src/dto/ft.user.dto.ts
  backend/src/dto/gameroom.list.dto.ts
  backend/src/dto/match.history.dto.ts
  backend/src/dto/rank.dto.ts
  backend/src/dto/response/chatroom.list.response.dto.ts
  backend/src/dto/response/chatroom.users.info.response.dto.ts
  backend/src/dto/response/gameroom.list.response.dto.ts
  backend/src/dto/response/gameroom.users.info.response.dto.ts
  backend/src/dto/response/online.users.response.dto.ts
  backend/src/dto/response/rank.list.response.dto.ts
  backend/src/dto/response/user.block.list.response.dto.ts
  backend/src/dto/response/user.friend.list.response.dto.ts
  backend/src/dto/response/user.info.response.dto.ts
  backend/src/dto/response/user.recent.match.history.response.dto.ts
  backend/src/dto/user.chat.dto.ts
  backend/src/dto/user.dto.ts
  backend/src/dto/user.status.dto.ts
  backend/src/enum/chatroom.mode.enum.ts
  backend/src/enum/gameroom.status.enum.ts
  backend/src/enum/match.result.enum.ts
  backend/src/enum/user.chat.mode.enum.ts
  backend/src/enum/user.status.enum.ts
Labels: be, feat

#48 [FE] FEAT: 랭킹 페이지 필터 버튼 추가 #38
  frontend/src/components/atoms/RankingFilter/RankingFilter.tsx
  frontend/src/components/atoms/RankingFilter/index.tsx
  frontend/src/pages/Ranking.tsx
Labels: feat, fe

#50 [FE] FEAT: 채팅방 초대 기능 추가
  frontend/src/api/auth.ts
  frontend/src/components/atoms/List/List.tsx
  frontend/src/components/atoms/ListItem/ListItem.tsx
  frontend/src/components/modules/ChatRoomButtons/ChatRoomButtons.tsx
  frontend/src/components/modules/ChatRoomButtons/index.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/ChatRoomUserList/index.tsx
  frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/modules/InviteModal/InviteModal.tsx
  frontend/src/components/modules/InviteModal/index.tsx
  frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
  frontend/src/components/modules/LoginButton/LoginButton.tsx
  frontend/src/components/modules/PaginationList/PaginationList.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/hooks/useInfoSetting.tsx
  frontend/src/pages/ChatRoom.tsx
  frontend/src/pages/Lobby.tsx
Labels: feat, fe

#54 [FE] REFACTOR: 코드 정리 #51
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth.ts
  frontend/src/api/axios.ts
  frontend/src/components/modules/ChooseGameModal/ChooseGameModal.tsx
  frontend/src/components/modules/LobbyCreateRoomButtons/LobbyCreateRoomButtons.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/LoginButton/LoginButton.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
  frontend/src/hooks/useCreateGameModal.tsx
  frontend/src/hooks/useCreateRoom.tsx
  frontend/src/hooks/useFirstLoginModal.tsx
  frontend/src/hooks/useQuickGameModal.tsx
  frontend/src/index.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Root.tsx
  frontend/src/state/.gitkeep
  frontend/src/state/LoadingState.tsx
Labels: feat, fe

#53 [BE] 로그인 후 유저 정보를 DB에 저장하도록 설정 #52
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/42/ft.strategy.ts
  backend/src/auth/42/mock.strategy.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/repository/auth.repository.interface.ts
  backend/src/auth/repository/auth.repository.ts
  backend/src/auth/session/session.serializer.ts
  backend/src/dto/ft.user.dto.ts
  backend/src/dto/user.dto.ts
  backend/src/entity/relation.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/enum/user.relation.enum.ts
  dev.docker-compose.yaml
  postgres/pong_arcade.sql
Labels: be, feat

#59 인증방식을 JWT 토큰으로 변경
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/42/ft.guard.ts
  backend/src/auth/42/ft.mock.strategy.ts
  backend/src/auth/42/mock.strategy.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.e2e-spec.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.auth.guard.ts
  backend/src/auth/jwt/jwt.sign.guard.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/auth/repository/auth.repository.interface.ts
  backend/src/auth/repository/auth.repository.ts
  backend/src/auth/session/session.guard.ts
  backend/src/auth/session/session.serializer.ts
  backend/src/chat/chat.geteway.ts
  backend/src/config/configuration.ts
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/middleware/middleware.d.ts
  backend/src/middleware/session.middleware.ts
  backend/src/user/user.controller.ts
Labels: be

#62 [FE] REFACTOR: 프론트 소켓 주석처리
  frontend/src/components/modules/Chat/Chat.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyCreateRoomButtons/LobbyCreateRoomButtons.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/index.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Root.tsx
  frontend/src/utils/ChatSocket.tsx
Labels: feat, fe

#64 [BE] FIX: JWT 토큰 보안 강화
  backend/src/auth/jwt/jwt.sign.guard.ts
Labels: be

#69 [BE] match_history, normal_stat, ladder_stat 테이블 추가
  backend/src/dto/match.history.dto.ts
  backend/src/entity/ladder.stat.entity.ts
  backend/src/entity/match.history.entity.ts
  backend/src/entity/normal.stat.entity.ts
  backend/src/enum/match.type.enum.ts
  postgres/pong_arcade.sql
Labels: be, feat

#67 [COMMON] nginx가 websocket 연결을 유지하도록 수정
  nginx/nginx.conf
Labels: common

#79 [FE] Ranking api 및 디자인 구현 #76
  backend/src/stat/stat.controller.ts
  frontend/src/api/ranking.ts
  frontend/src/components/modules/ChatRoomInvitePagination/ChatRoomInvitePagination.tsx
  frontend/src/components/modules/ChatRoomInviteUserItem/ChatRoomInviteUserItem.tsx
  frontend/src/components/modules/ChatRoomUserListPagination/ChatRoomUserListPagination.tsx
  frontend/src/components/modules/InviteModal/InviteModal.tsx
  frontend/src/components/modules/LobbyChatRoomPagination/LobbyChatRoomPagination.tsx
  frontend/src/components/modules/LobbyGameRoomPagination/LobbyGameRoomPagination.tsx
  frontend/src/components/modules/LobbyUserItem/LobbyUserItem.tsx
  frontend/src/components/modules/LobbyUserListPagination/LobbyUserListPagination.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RankingItem/RankingItem.tsx
  frontend/src/components/modules/RankingItem/index.tsx
  frontend/src/components/modules/RankingPagination/RankingPagination.tsx
  frontend/src/hooks/useLobbyUserList.tsx
  frontend/src/hooks/useRankList.tsx
  frontend/src/pages/Ranking.tsx
Labels: feat, fe

#80 [FE] Stat api and design #75
  backend/src/dto/match.history.dto.ts
  backend/src/relation/block.controller.ts
  backend/src/relation/friends.controller.ts
  backend/src/stat/stat.controller.ts
  backend/src/user/user.controller.ts
  frontend/src/api/stat.ts
  frontend/src/api/users.ts
  frontend/src/components/atoms/List/List.tsx
  frontend/src/components/atoms/List/index.tsx
  frontend/src/components/atoms/ListItem/ListItem.tsx
  frontend/src/components/atoms/ListItem/index.tsx
  frontend/src/components/modules/AttributeGroup/AttributeGroup.tsx
  frontend/src/components/modules/AttributeGroup/index.tsx
  frontend/src/components/modules/LobbyCreateRoomButtonGroup/LobbyCreateRoomButtonGroup.tsx
  frontend/src/components/modules/LobbyRoomListTypeChoiceButtonGroup/LobbyRoomListTypeChoiceButtonGroup.tsx
  frontend/src/components/modules/LobbyUserItem/LobbyUserItem.tsx
  frontend/src/components/modules/Menu/Menu.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RankingPagination/RankingPagination.tsx
  frontend/src/components/modules/RoomTypeCheckBoxGroup/RoomTypeCheckBoxGroup.tsx
  frontend/src/components/modules/StatList/StatList.tsx
  frontend/src/components/modules/StatList/index.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/modules/UserListTypeChoiceButtonGroup/UserListTypeChoiceButtonGroup.tsx
  frontend/src/components/templates/StatTemplate/StatTemplate.tsx
  frontend/src/components/templates/StatTemplate/index.tsx
  frontend/src/hooks/useLobbyUserList.tsx
  frontend/src/hooks/useStatList.tsx
  frontend/src/pages/Stat.tsx
Labels: feat, fe

#82 [BE] Request DTO 추가
  backend/src/dto/request/chatroom.create.request.dto.ts
  backend/src/dto/request/gameroom.create.request.dto.ts
  backend/src/dto/response/gameroom.users.info.response.dto.ts
  backend/src/enum/gameroom.mode.enum.ts
Labels: be, feat

#85 [FE] 모달창 esc 기능 추가
  frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/modules/ModalTitle/ModalTitle.tsx
  frontend/src/components/modules/QuickGameModal/QuickGameModal.tsx
  frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/styles/GlobalStyle.ts
Labels: feat, fe

#93 [BE] DTO에 swagger 명세 추가
  backend/src/dto/chatroom.list.dto.ts
  backend/src/dto/gameroom.list.dto.ts
  backend/src/dto/match.history.dto.ts
  backend/src/dto/rank.dto.ts
  backend/src/dto/request/chatroom.create.request.dto.ts
  backend/src/dto/request/gameroom.create.request.dto.ts
  backend/src/dto/response/chatroom.list.response.dto.ts
  backend/src/dto/response/chatroom.users.info.response.dto.ts
  backend/src/dto/response/gameroom.list.response.dto.ts
  backend/src/dto/response/gameroom.users.info.response.dto.ts
  backend/src/dto/response/online.users.response.dto.ts
  backend/src/dto/response/rank.list.response.dto.ts
  backend/src/dto/response/user.block.list.response.dto.ts
  backend/src/dto/response/user.friend.list.response.dto.ts
  backend/src/dto/response/user.info.response.dto.ts
  backend/src/dto/response/user.recent.match.history.response.dto.ts
  backend/src/dto/user.chat.dto.ts
  backend/src/dto/user.dto.ts
  backend/src/dto/user.status.dto.ts
  backend/src/enum/user.status.enum.ts
  backend/src/mock/mock.repository.ts
Labels: be, feat

#97 [FE] 로비 친구 추가 / 삭제 기능, 차단 추가 / 해제 기능 추가 #73 #74
  backend/src/relation/block.controller.ts
  backend/src/relation/friends.controller.ts
  backend/src/user/user.controller.ts
  frontend/src/api/axios.ts
  frontend/src/api/ranking.ts
  frontend/src/api/stat.ts
  frontend/src/api/users.ts
  frontend/src/components/atoms/Button/Button.tsx
  frontend/src/components/atoms/Typography/Typography.tsx
  frontend/src/components/modules/ChatRoomButtonGroup/ChatRoomButtonGroup.tsx
  frontend/src/components/modules/ChatRoomInviteUserItem/ChatRoomInviteUserItem.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/modules/ExitConfirmModal/ExitConfirmModal.tsx
  frontend/src/components/modules/ExitConfirmModal/index.tsx
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
  frontend/src/components/modules/GeneralMenu/index.tsx
  frontend/src/components/modules/InviteConfirmModal/InviteConfirmModal.tsx
  frontend/src/components/modules/InviteConfirmModal/index.tsx
  frontend/src/components/modules/InviteModal/InviteModal.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyUserItem/LobbyUserItem.tsx
  frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/LogoutConfirmModal/LogoutConfirmModal.tsx
  frontend/src/components/modules/LogoutConfirmModal/index.tsx
  frontend/src/components/modules/Menu/Menu.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RelationConfirmModal/RelationConfirmModal.tsx
  frontend/src/components/modules/RelationConfirmModal/index.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/hooks/useFirstLoginModal.tsx
  frontend/src/hooks/useLobbyUserList.tsx
  frontend/src/hooks/useMenu.tsx
  frontend/src/hooks/useRelation.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Root.tsx
  frontend/src/state/BlockUsersState.tsx
  frontend/src/state/FriendUsersState.tsx
  frontend/src/state/LoginState.tsx
  frontend/src/state/OnlineUsersState.tsx
  frontend/src/utils/ChatSocket.tsx
Labels: feat, fe

#99 [BE] FEAT: user && relation mock data logic #98
  backend/src/auth/auth.controller.ts
  backend/src/mock/mock.repository.ts
  backend/src/relation/block.controller.ts
  backend/src/relation/friends.controller.ts
  backend/src/user/user.controller.ts
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
Labels: be

#106 [BE] chat API 구현
  backend/src/chat/chat.geteway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/chat/chatroom.entity.ts
  backend/src/dto/request/chatroom.change.info.request.dto.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
Labels: be, feat

#107 [COMMON] 로비 채팅방 리스트 mock 데이터 생성 && 디자인 #101
  backend/src/auth/jwt/jwt.sign.guard.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/mock/mock.repository.ts
  backend/src/relation/block.controller.ts
  backend/src/relation/friends.controller.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/axios.ts
  frontend/src/api/chatRoom.ts
  frontend/src/api/users.ts
  frontend/src/assets/chat.svg
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
  frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
  frontend/src/components/modules/ErrorModal/ErrorModal.tsx
  frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
  frontend/src/components/modules/LobbyChatRoomItem/index.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyChatRoomPagination/LobbyChatRoomPagination.tsx
  frontend/src/components/modules/LobbyRoomListTypeChoiceButtonGroup/LobbyRoomListTypeChoiceButtonGroup.tsx
  frontend/src/components/modules/LoginButton/LoginButton.tsx
  frontend/src/components/modules/ModifyChatRoomModal/ModifyChatRoomModal.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RoomTypeCheckBoxGroup/RoomTypeCheckBoxGroup.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/hooks/useChatRoomForm.tsx
  frontend/src/hooks/useGameRoomForm.tsx
  frontend/src/hooks/useLobbyUserList.tsx
  frontend/src/hooks/useModifyChatRoomForm.tsx
  frontend/src/hooks/useRelation.tsx
  frontend/src/index.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Root.tsx
  frontend/src/state/LoadingState.tsx
  frontend/src/utils/removeJWT.ts
Labels: feat, common

#113 [COMMON] 로비 프로필 개인 정보로 변경
  backend/src/chat/chat.geteway.ts
  backend/src/chat/chat.service.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/user/user.controller.ts
  frontend/src/api/axios.ts
  frontend/src/api/users.ts
  frontend/src/components/atoms/Avatar/Avatar.tsx
  frontend/src/components/atoms/Board/Board.tsx
  frontend/src/components/atoms/CloseButton/CloseButton.tsx
  frontend/src/components/atoms/FullSpinner/FullSpinner.tsx
  frontend/src/components/atoms/FullSpinner/index.tsx
  frontend/src/components/atoms/GridList/GridList.tsx
  frontend/src/components/atoms/GridList/index.tsx
  frontend/src/components/atoms/Input/Input.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/ContentList/ContentList.tsx
  frontend/src/components/modules/ContentList/index.tsx
  frontend/src/components/modules/ContentListWrapper/ContentListWrapper.tsx
  frontend/src/components/modules/ContentListWrapper/index.tsx
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
  frontend/src/components/modules/InviteModal/InviteModal.tsx
  frontend/src/components/modules/LobbyGameRoomPagination/LobbyGameRoomPagination.tsx
  frontend/src/components/modules/LobbyUserList/LobbyUserList.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/LoginButton/LoginButton.tsx
  frontend/src/components/modules/LogoutButton/LogoutButton.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
  frontend/src/hooks/useFirstLoginModal.tsx
  frontend/src/hooks/useLoading.tsx
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/hooks/useLobbyUserList.tsx
  frontend/src/hooks/useRelation.tsx
  frontend/src/index.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Root.tsx
  frontend/src/state/BlockUsersState.tsx
  frontend/src/state/FriendUsersState.tsx
  frontend/src/state/InfoState.tsx
  frontend/src/state/LoadingState.tsx
  frontend/src/state/LoginState.tsx
  frontend/src/state/OnlineUsersState.tsx
  frontend/src/utils/cookie.ts
Labels: feat, common

#117 [BE] 유저정보 변경 API 구현
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/dto/request/update.user.info.request.dto.ts
  backend/src/user/repository/user.repository.interface.ts
  backend/src/user/repository/user.repository.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/uploads/.gitkeep
  package-lock.json
  package.json
Labels: be, feat

#118 Be/feat dao#100
  backend/src/dto/user.relation.dto.ts
  backend/src/entity/relation.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/relation/block.controller.ts
  backend/src/relation/block.service.ts
  backend/src/relation/friends.controller.ts
  backend/src/relation/friends.service.ts
  backend/src/relation/relation.module.ts
  backend/src/status/status.module.ts
  backend/src/user/repository/user.repository.interface.ts
  backend/src/user/repository/user.repository.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  package-lock.json
  package.json
  postgres/pong_arcade.sql
Labels: be, feat

#124 [BE] GameRoom 관련 API 구현
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/game/gameroom.controller.ts
  backend/src/game/gameroom.entity.ts
  backend/src/game/gameroom.service.ts
  backend/src/user/user.module.ts
Labels: be, feat

#129 [FE] 유저 정보 업데이트 구현 #45
  frontend/src/api/axios.ts
  frontend/src/api/room.ts
  frontend/src/api/users.ts
  frontend/src/components/atoms/Avatar/Avatar.tsx
  frontend/src/components/atoms/ChatList/ChatList.tsx
  frontend/src/components/modules/Chat/Chat.tsx
  frontend/src/components/modules/ChatInput/ChatInput.tsx
  frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
  frontend/src/components/modules/ChatRoomItem/index.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
  frontend/src/components/modules/ErrorModal/ErrorModal.tsx
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
  frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RelationConfirmModal/RelationConfirmModal.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
  frontend/src/hooks/useChatRoomForm.tsx
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/hooks/useMenu.tsx
  frontend/src/hooks/useModifyChatRoomForm.tsx
  frontend/src/hooks/useRelation.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/state/ChatRoomState.tsx
Labels: feat, fe

#131 [BE] FIX: Blob 형태의 파일 업로드 버그 수정 #128
  .gitignore
  backend/src/app.module.ts
  backend/src/config/configuration.ts
  backend/src/user/user.controller.ts
  frontend/src/api/users.ts
  nginx/nginx.conf
Labels: bug, be

#133 [BE] FIX: stat API 관련 버그 수정 #132
  backend/src/auth/auth.module.ts
  backend/src/auth/repository/auth.repository.ts
  backend/src/stat/repository/stat.repository.ts
Labels: bug, be

#135 [FE] FEAT: 랭킹방 필터 기능 및 샘플 데이터로 확인 #102
  frontend/src/api/ranking.ts
  frontend/src/components/atoms/RankingFilter/RankingFilter.tsx
  frontend/src/components/modules/RankingItem/RankingItem.tsx
  frontend/src/hooks/useRankList.tsx
  frontend/src/hooks/useRanking.tsx
  frontend/src/hooks/useRelation.tsx
  frontend/src/pages/Ranking.tsx
  postgres/pong_arcade_sample.sql
Labels: feat, fe

#138 gFe/dev/feat stat sample data and design/#136
  frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/RelationConfirmModal/RelationConfirmModal.tsx
  frontend/src/components/modules/StatList/StatList.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/modules/UserInfoSettingModal/UserInfoSettingModal.tsx
  frontend/src/hooks/useBlockUsers.tsx
  frontend/src/hooks/useFriendUsers.tsx
  frontend/src/hooks/useRelation.tsx
Labels: feat, fe

#140 [BE] FEAT: Controller에 UseGuards, ApiBearerAuth 추가 #134
  backend/src/auth/auth.controller.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/game/gameroom.controller.ts
  backend/src/stat/stat.controller.ts
Labels: be, feat

#142 [FE] FEAT: axios error 처리 #139
  frontend/src/api/ranking.ts
  frontend/src/components/modules/UnauthorizedModal/UnauthorizedModal.tsx
  frontend/src/components/modules/UnauthorizedModal/index.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/pages/Root.tsx
  frontend/src/state/ErrorState.tsx
  frontend/src/utils/cookie.ts
Labels: feat, fe

#144 [FE] FEAT: 채팅방 입장 승인 거부 처리 #143
  frontend/src/api/axios.ts
  frontend/src/api/ranking.ts
  frontend/src/api/room.ts
  frontend/src/components/modules/ChatRoomUserListPagination/ChatRoomUserListPagination.tsx
  frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
  frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
  frontend/src/components/modules/ErrorModal/ErrorModal.tsx
  frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyChatRoomPagination/LobbyChatRoomPagination.tsx
  frontend/src/components/modules/LobbyUserListPagination/LobbyUserListPagination.tsx
  frontend/src/components/modules/ModifyChatRoomModal/ModifyChatRoomModal.tsx
  frontend/src/hooks/useLobbyData.tsx
Labels: feat, fe

#151 [FE] REFACTOR: 메뉴바 귓속말 삭제
  frontend/src/components/modules/GeneralMenu/GeneralMenu.tsx
Labels: fe

#153 [BE] 2차 인증 기능 추가 #149
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/repository/auth.repository.interface.ts
  backend/src/auth/repository/auth.repository.ts
  backend/src/config/configuration.ts
  backend/src/config/mailer.config.ts
  backend/src/dto/user.auth.dto.ts
  backend/src/entity/two.factor.auth.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/utils/email..sender.component.ts
  backend/src/utils/templates/two.factor.email.hbs
  backend/src/utils/utils.module.ts
  postgres/pong_arcade.sql
  postgres/pong_arcade_sample.sql
Labels: be, feat

#155 [FE] FEAT: 채팅방 초대 모달 추가
  frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
  frontend/src/components/modules/ChatInviteModal/index.tsx
  frontend/src/pages/Lobby.tsx
Labels: feat, fe

#157 [FE] FEAT: 최근전적 페이지 모달로 변경
  frontend/src/api/stat.ts
  frontend/src/components/modules/StatModal/StatModal.tsx
  frontend/src/components/modules/StatModal/index.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/components/templates/StatTemplate/StatTemplate.tsx
  frontend/src/components/templates/StatTemplate/index.tsx
  frontend/src/hooks/useStatList.tsx
  frontend/src/index.tsx
  frontend/src/pages/Stat.tsx
Labels: feat, fe

#158 [FE] FEAT: 2FA 추가 #156
  backend/src/auth/auth.controller.ts
  backend/src/auth/repository/auth.repository.ts
  frontend/src/api/auth.ts
  frontend/src/api/axios.ts
  frontend/src/components/atoms/Input/Input.tsx
  frontend/src/components/modules/Confirm2FAModal/Confirm2FAModal.tsx
  frontend/src/components/modules/Confirm2FAModal/index.tsx
  frontend/src/components/modules/FailModal/FailModal.tsx
  frontend/src/components/modules/FailModal/index.tsx
  frontend/src/components/modules/LobbyUserProfile/LobbyUserProfile.tsx
  frontend/src/components/modules/StatConfirmModal/index.tsx
  frontend/src/components/modules/SuccessModal/SuccessModal.tsx
  frontend/src/components/modules/SuccessModal/index.tsx
  frontend/src/components/modules/UnauthorizedModal/UnauthorizedModal.tsx
  frontend/src/components/modules/UserInfoModal/UserInfoModal.tsx
  frontend/src/index.tsx
  frontend/src/pages/Login2FA.tsx
  frontend/src/utils/removeJWT.ts
  frontend/src/utils/token.ts
Labels: feat, fe

#163 [FE] FEAT: 채팅방 비밀번호 입력 모달 추가 #161
  backend/src/chat/chat.service.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/dto/response/chatroom.create.users.info.response.dto.ts
  backend/src/dto/response/chatroom.users.info.response.dto.ts
  frontend/src/api/room.ts
  frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
  frontend/src/components/modules/ChatRoomPasswordModal/ChatRoomPasswordModal.tsx
  frontend/src/components/modules/ChatRoomPasswordModal/index.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
  frontend/src/components/modules/LobbyChatRoomItem/LobbyChatRoomItem.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/pages/ChatRoom.tsx
Labels: feat, fe
