Repository Pong-Arcade/ft_transcendence, pull requests merged in 2023-03, with the labels that each got.

#164 [FE] FEAT: 채팅방 비밀번호 변경 모달 기능 추가 #162
  backend/src/chat/chat.service.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/dto/response/chatroom.create.users.info.response.dto.ts
  backend/src/utils/email..sender.component.ts
  frontend/src/api/room.ts
  frontend/src/api/users.ts
  frontend/src/components/modules/ChatRoomPasswordModal/ChatRoomPasswordModal.tsx
  frontend/src/components/modules/ChatRoomPasswordModify/ChatRoomPasswordModify.tsx
  frontend/src/components/modules/FailModal/FailModal.tsx
  frontend/src/components/modules/ModifyChatRoomModal/ModifyChatRoomModal.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/SuccessModal/SuccessModal.tsx
  frontend/src/hooks/useModifyChatRoomForm.tsx
  frontend/src/pages/ChatRoom.tsx
  frontend/src/pages/Login2FA.tsx
Labels: feat, fe

#171 [FE] FEAT: quick match 게임 기능 추가 #166
  backend/src/game/game.gateway.ts
  backend/src/game/gameroom.controller.ts
  backend/src/game/gameroom.service.ts
  frontend/src/api/room.ts
  frontend/src/components/modules/ChooseGameModal/ChooseGameModal.tsx
  frontend/src/components/modules/LobbyCreateRoomButtonGroup/LobbyCreateRoomButtonGroup.tsx
  frontend/src/components/modules/Pagination/Pagination.tsx
  frontend/src/components/modules/QuickGameModal/QuickGameModal.tsx
  frontend/src/event/GameEvent/lobbyGameEvent.ts
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/pages/Lobby.tsx
Labels: feat, fe

#174 [BE] 전체 온라인 유저 정보 API 버그 수정
  backend/src/user/repository/user.repository.interface.ts
  backend/src/user/repository/user.repository.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: bug, be

#182 [BE] FIX: 유저 생성 시, 트랜잭션 관리
  backend/src/auth/repository/auth.repository.ts
Labels: enhancement, be

#185 [BE] ENHANCE: DDL 일부 수정 #184
  backend/src/auth/auth.controller.ts
  backend/src/game/game.gateway.ts
  backend/src/game/gameConfig.json
  backend/src/game/gameInstance.ts
  backend/src/game/gameroom.entity.ts
  backend/src/user/user.service.ts
  frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
  frontend/src/components/modules/GameBoard/GameBoard.tsx
  frontend/src/components/modules/GameBoard/index.tsx
  frontend/src/components/modules/GameCountDown/GameCountDown.tsx
  frontend/src/components/modules/GameCountDown/index.tsx
  frontend/src/components/modules/GameStart/GameStart.tsx
  frontend/src/components/modules/GameStart/index.tsx
  frontend/src/event/GameEvent/gameStartEvent.ts
  frontend/src/event/GameEvent/lobbyGameEvent.ts
  frontend/src/pages/GameRoom.tsx
  frontend/src/state/GameBoardState.ts
  postgres/pong_arcade.sql
Labels: enhancement, be

#190 [COMMON] frontend backend 게임 기능 연결 #168
  backend/src/game/game.gateway.ts
  backend/src/game/gameConfig.json
  frontend/src/api/room.ts
  frontend/src/components/modules/CreateGameRoomModal/CreateGameRoomModal.tsx
  frontend/src/components/modules/FailModal/FailModal.tsx
  frontend/src/components/modules/GameBoard/GameBoard.tsx
  frontend/src/components/modules/GameFinish/GameFinish.tsx
  frontend/src/components/modules/GameFinish/index.tsx
  frontend/src/components/modules/ModalTitle/ModalTitle.tsx
  frontend/src/event/GameEvent/gameBoardEvent.ts
  frontend/src/event/GameEvent/gameStartEvent.ts
  frontend/src/hooks/useGameRoomForm.tsx
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/pages/GameRoom.tsx
Labels: feat, fe

#197 [FE] FEAT: ajax 응답 대기 시 로딩 추가 #170
  backend/src/chat/chat.geteway.ts
  backend/src/chat/chatroom.controller.ts
  backend/src/game/game.gateway.ts
  backend/src/relation/friends.service.ts
  backend/src/user/user.controller.ts
  frontend/src/api/room.ts
  frontend/src/api/users.ts
  frontend/src/components/modules/ChatConfirmModal/ChatConfirmModal.tsx
  frontend/src/components/modules/ChatInviteModal/ChatInviteModal.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/CreateChatRoomModal/CreateChatRoomModal.tsx
  frontend/src/components/modules/GameFinish/GameFinish.tsx
  frontend/src/components/modules/InviteConfirmModal/InviteConfirmModal.tsx
  frontend/src/components/modules/InviteModal/InviteModal.tsx
  frontend/src/components/modules/LobbyChatRoomList/LobbyChatRoomList.tsx
  frontend/src/components/modules/LobbyCreateRoomButtonGroup/LobbyCreateRoomButtonGroup.tsx
  frontend/src/components/templates/LobbyTemplate/LobbyTemplate.tsx
  frontend/src/event/ChatEvent/lobbyChatEvent.ts
  frontend/src/event/GameEvent/gameBoardEvent.ts
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/hooks/useModal.tsx
  frontend/src/index.tsx
  frontend/src/pages/Lobby.tsx
Labels: feat, fe

#204 Be/refactor/#203
  backend/src/app.module.ts
  backend/src/chat/chat.geteway.ts
  backend/src/chat/chat.module.ts
  backend/src/chat/chat.service.ts
  backend/src/dto/request/chatroom.invite.request.dto.ts
  backend/src/game/game.gateway.ts
  backend/src/game/game.module.ts
  backend/src/game/gameInstance.ts
  backend/src/game/gameroom.controller.ts
  backend/src/game/gameroom.service.ts
  backend/src/relation/block.service.ts
  backend/src/relation/friends.service.ts
  backend/src/relation/relation.module.ts
  backend/src/stat/repository/stat.repository.ts
  backend/src/stat/stat.module.ts
  backend/src/stat/stat.service.ts
  backend/src/status/status.entity.ts
  backend/src/status/status.module.ts
  backend/src/status/status.service.ts
  backend/src/user/repository/user.repository.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
Labels: be, refactor

#214 [FE] 게임 결과 모달 디자인 수정
  backend/src/game/game.gateway.ts
  frontend/src/components/atoms/GameChatList/GameChatList.tsx
  frontend/src/components/atoms/GameChatList/index.tsx
  frontend/src/components/modules/ConfirmModal/ConfirmModal.tsx
  frontend/src/components/modules/GameBoard/GameBoard.tsx
  frontend/src/components/modules/GameChat/index.tsx
  frontend/src/components/modules/GameFinish/GameFinish.tsx
  frontend/src/components/modules/GameInput/index.tsx
  frontend/src/components/modules/InviteGameModal/InviteGameModal.tsx
  frontend/src/hooks/useFirstLoginModal.tsx
  frontend/src/pages/GameRoom.tsx
Labels: feat, fe

#218 [BE] FIX: user 정보가 캐싱되지 않는 버그 수정 #215
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: bug, be

#223 [COMMON] 소켓 인증 기능 추가 #216
  backend/src/chat/chat.geteway.ts
  backend/src/chat/chat.module.ts
  backend/src/game/game.gateway.ts
  frontend/src/event/GameEvent/gameRoomEvent.ts
  frontend/src/event/GameEvent/lobbyGameEvent.ts
  frontend/src/pages/ChatRoom.tsx
  frontend/src/state/GameSocket.ts
  frontend/src/utils/ChatSocket.tsx
Labels: be, feat

#229 [BE] 귓속말 관련 버그 제거
  backend/src/game/game.gateway.ts
  backend/src/game/gameroom.controller.ts
  backend/src/game/gameroom.service.ts
  frontend/src/components/atoms/GameChatList/GameChatList.tsx
Labels: be

#235 [FE] 에러 모달 떴을 시 로비로 이동 || 현재 페이지에 남기 || 로그인 페이지로 이동으로 구분
  frontend/src/components/modules/ChatRoomItem/ChatRoomItem.tsx
  frontend/src/components/modules/GlobalErrorModal/GlobalErrorModal.tsx
  frontend/src/hooks/useFriendUsers.tsx
  frontend/src/pages/ChatRoom.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/pages/Lobby.tsx
  frontend/src/state/ErrorState.ts
  frontend/src/state/GameSocket.ts
  nginx/Dockerfile
Labels: feat, fe

#238 [BE] FIX: 유저가 존재하지 않을 때, 유저 상세정보 API 오류 수정
  backend/src/stat/repository/stat.repository.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
Labels: bug, be

#242 [BE] REFACT: login/callback에서의 동작을 리팩토링
  backend/src/auth/auth.service.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/auth/repository/auth.repository.interface.ts
  backend/src/auth/repository/auth.repository.ts
  backend/src/user/user.service.ts
Labels: be, refactor

#246 [COMMON] 서버 에러 발생 시 에러 핸들링
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/global.exception.filter.ts
  frontend/src/components/modules/GlobalErrorModal/GlobalErrorModal.tsx
  frontend/src/components/modules/InternalServerErrorModal/InternalServerErrorModal.tsx
  frontend/src/components/modules/InternalServerErrorModal/index.tsx
Labels: enhancement, be, fe

#247 [FE] FEAT: 뒤로가기 앞으로 가기 버튼 로직 구현
  backend/src/chat/chatroom.controller.ts
  backend/src/game/gameroom.controller.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/room.ts
  frontend/src/components/modules/ChatRoomButtonGroup/ChatRoomButtonGroup.tsx
  frontend/src/components/modules/ChatRoomMenu/ChatRoomMenu.tsx
  frontend/src/components/modules/ChatRoomUserList/ChatRoomUserList.tsx
  frontend/src/components/modules/GlobalErrorModal/GlobalErrorModal.tsx
  frontend/src/components/modules/LobbyGameRoomItem/LobbyGameRoomItem.tsx
  frontend/src/components/modules/LoginButton/LoginButton.tsx
  frontend/src/event/GameEvent/chatRoomGameEvent.ts
  frontend/src/event/GameEvent/lobbyGameEvent.ts
  frontend/src/hooks/useLobbyData.tsx
  frontend/src/pages/ChatRoom.tsx
  frontend/src/pages/GameRoom.tsx
  frontend/src/pages/Lobby.tsx
Labels: feat, fe
